name: Update Changelog

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Show workspace layout
        run: |
          echo "PWD: $(pwd)"
          ls -la
          sudo apt-get update -y >/dev/null 2>&1 || true
          sudo apt-get install -y tree >/dev/null 2>&1 || true
          echo "Repository tree (2 levels):"
          tree -L 2 || true

      - name: Collect commit messages in this push
        id: commits
        run: |
          FROM_SHA="${{ github.event.before }}"
          TO_SHA="${{ github.sha }}"
          if [ -z "$FROM_SHA" ] || [ "$FROM_SHA" = "0000000000000000000000000000000000000000" ]; then
            MESSAGES="$(git log -1 --pretty=format:'- (%an) %s')"
          else
            MESSAGES="$(git log --pretty=format:'- (%an) %s' "${FROM_SHA}..${TO_SHA}")"
          fi
          echo "messages<<EOF" >> $GITHUB_OUTPUT
          echo "$MESSAGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Append to CHANGELOG.md
        run: |
          DATE="$(date +'%Y-%m-%d')"
          REPO="${{ github.repository }}"
          SHORT="${GITHUB_SHA::7}"
          COMMIT_URL="https://github.com/${REPO}/commit/${GITHUB_SHA}"
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi
          # Prepend the new entry right after the header so newest is on top
          HEADER_LINE="$(head -n 1 CHANGELOG.md || echo '# Changelog')"
          tail -n +2 CHANGELOG.md > CHANGELOG.body || true
          {
            echo "${HEADER_LINE}"
            echo ""
            echo "## ${DATE} — commit ${SHORT} (${COMMIT_URL})"
            echo "${{ steps.commits.outputs.messages }}"
            echo ""
            cat CHANGELOG.body || true
          } > CHANGELOG.tmp
          rm -f CHANGELOG.body
          mv CHANGELOG.tmp CHANGELOG.md

      - name: Show CHANGELOG.md (head)
        run: |
          echo "CHANGELOG.md preview:"
          sed -n '1,120p' CHANGELOG.md || true

      - name: Show workspace layout (post-change)
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "Repository tree (2 levels) after changes:"
          tree -L 2 || true

      - name: Commit and push
        run: |
          set -e
          git status --porcelain
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Stage first to avoid unstaged changes blocking rebase
          git add CHANGELOG.md
          # Commit only if there are staged changes
          if git diff --cached --quiet; then
            echo "No changelog changes to commit."
            exit 0
          fi
          git commit -m "chore(changelog): update for ${GITHUB_SHA::7} [skip ci]"
          # Rebase with autostash to handle concurrent changes
          git pull --rebase --autostash || true
          # Push (retry once if needed)
          git push || (git pull --rebase --autostash && git push)
